// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SchoolSystem.Api.Data;

#nullable disable

namespace SchoolSystem.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SchoolSystem.Core.Models.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassSubjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClassSubjectId");

                    b.HasIndex("StudentId", "ClassSubjectId", "Date")
                        .IsUnique();

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GradeId")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeroomUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("SchoolYear")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HomeroomUserId");

                    b.HasIndex("GradeId", "Name", "SchoolYear")
                        .IsUnique();

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.ClassSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<int?>("TeacherUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherUserId");

                    b.HasIndex("ClassId", "SubjectId")
                        .IsUnique();

                    b.ToTable("ClassSubjects");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MonthlyReportId")
                        .HasColumnType("integer");

                    b.Property<int>("ParentUserId")
                        .HasColumnType("integer");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SemesterReportId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("YearlyReportId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MonthlyReportId");

                    b.HasIndex("ParentUserId");

                    b.HasIndex("SemesterReportId");

                    b.HasIndex("YearlyReportId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.GradebookEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassSubjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MaxScore")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClassSubjectId");

                    b.HasIndex("StudentId");

                    b.ToTable("GradebookEntries");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.MonthlyReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Month")
                        .HasColumnType("smallint");

                    b.Property<short>("SchoolYear")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SubmittedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SubmittedBy");

                    b.HasIndex("ClassId", "Month", "SchoolYear")
                        .IsUnique();

                    b.ToTable("MonthlyReports");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.MonthlyReportEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short?>("Rank")
                        .HasColumnType("smallint");

                    b.Property<int>("ReportId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TotalScore")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("ReportId", "StudentId")
                        .IsUnique();

                    b.ToTable("MonthlyReportEntries");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.MonthlyScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassSubjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FinalScore")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<short>("Month")
                        .HasColumnType("smallint");

                    b.Property<short>("SchoolYear")
                        .HasColumnType("smallint");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SubmittedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubmittedBy");

                    b.HasIndex("ClassSubjectId", "StudentId", "Month", "SchoolYear")
                        .IsUnique();

                    b.ToTable("MonthlyScores");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.ParentStudent", b =>
                {
                    b.Property<int>("ParentUserId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ParentUserId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("ParentStudents");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.SemesterReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("SchoolYear")
                        .HasColumnType("smallint");

                    b.Property<short>("Semester")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SubmittedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SubmittedBy");

                    b.HasIndex("ClassId", "Semester", "SchoolYear")
                        .IsUnique();

                    b.ToTable("SemesterReports");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.SemesterReportEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short?>("Rank")
                        .HasColumnType("smallint");

                    b.Property<int>("ReportId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TotalScore")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("ReportId", "StudentId")
                        .IsUnique();

                    b.ToTable("SemesterReportEntries");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.SemesterScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassSubjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("FinalScore")
                        .HasColumnType("numeric");

                    b.Property<short>("SchoolYear")
                        .HasColumnType("smallint");

                    b.Property<short>("Semester")
                        .HasColumnType("smallint");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("ClassSubjectId", "StudentId", "Semester", "SchoolYear")
                        .IsUnique();

                    b.ToTable("SemesterScores");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<string>("Contact")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contact")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.YearlyReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("SchoolYear")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SubmittedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SubmittedBy");

                    b.HasIndex("ClassId", "SchoolYear")
                        .IsUnique();

                    b.ToTable("YearlyReports");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.YearlyReportEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short?>("Rank")
                        .HasColumnType("smallint");

                    b.Property<int>("ReportId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TotalScore")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("ReportId", "StudentId")
                        .IsUnique();

                    b.ToTable("YearlyReportEntries");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.YearlyScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassSubjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("FinalScore")
                        .HasColumnType("numeric");

                    b.Property<short>("SchoolYear")
                        .HasColumnType("smallint");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("ClassSubjectId", "StudentId", "SchoolYear")
                        .IsUnique();

                    b.ToTable("YearlyScores");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.Attendance", b =>
                {
                    b.HasOne("SchoolSystem.Core.Models.ClassSubject", "ClassSubject")
                        .WithMany("Attendances")
                        .HasForeignKey("ClassSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolSystem.Core.Models.Student", "Student")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassSubject");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.Class", b =>
                {
                    b.HasOne("SchoolSystem.Core.Models.Grade", "Grade")
                        .WithMany("Classes")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolSystem.Core.Models.User", "HomeroomTeacher")
                        .WithMany("HomeroomClasses")
                        .HasForeignKey("HomeroomUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Grade");

                    b.Navigation("HomeroomTeacher");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.ClassSubject", b =>
                {
                    b.HasOne("SchoolSystem.Core.Models.Class", "Class")
                        .WithMany("ClassSubjects")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolSystem.Core.Models.Subject", "Subject")
                        .WithMany("ClassSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolSystem.Core.Models.User", "Teacher")
                        .WithMany("TeachingClassSubjects")
                        .HasForeignKey("TeacherUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Class");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.Feedback", b =>
                {
                    b.HasOne("SchoolSystem.Core.Models.MonthlyReport", "MonthlyReport")
                        .WithMany("Feedbacks")
                        .HasForeignKey("MonthlyReportId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SchoolSystem.Core.Models.User", "Parent")
                        .WithMany("ParentFeedbacks")
                        .HasForeignKey("ParentUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolSystem.Core.Models.SemesterReport", "SemesterReport")
                        .WithMany("Feedbacks")
                        .HasForeignKey("SemesterReportId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SchoolSystem.Core.Models.YearlyReport", "YearlyReport")
                        .WithMany("Feedbacks")
                        .HasForeignKey("YearlyReportId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MonthlyReport");

                    b.Navigation("Parent");

                    b.Navigation("SemesterReport");

                    b.Navigation("YearlyReport");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.GradebookEntry", b =>
                {
                    b.HasOne("SchoolSystem.Core.Models.ClassSubject", "ClassSubject")
                        .WithMany("GradebookEntries")
                        .HasForeignKey("ClassSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolSystem.Core.Models.Student", "Student")
                        .WithMany("GradebookEntries")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassSubject");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.MonthlyReport", b =>
                {
                    b.HasOne("SchoolSystem.Core.Models.Class", "Class")
                        .WithMany("MonthlyReports")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolSystem.Core.Models.User", "SubmittedByUser")
                        .WithMany("SubmittedMonthlyReports")
                        .HasForeignKey("SubmittedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Class");

                    b.Navigation("SubmittedByUser");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.MonthlyReportEntry", b =>
                {
                    b.HasOne("SchoolSystem.Core.Models.MonthlyReport", "Report")
                        .WithMany("Entries")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolSystem.Core.Models.Student", "Student")
                        .WithMany("MonthlyReportEntries")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.MonthlyScore", b =>
                {
                    b.HasOne("SchoolSystem.Core.Models.ClassSubject", "ClassSubject")
                        .WithMany("MonthlyScores")
                        .HasForeignKey("ClassSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolSystem.Core.Models.Student", "Student")
                        .WithMany("MonthlyScores")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolSystem.Core.Models.User", "SubmittedByUser")
                        .WithMany("SubmittedMonthlyScores")
                        .HasForeignKey("SubmittedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ClassSubject");

                    b.Navigation("Student");

                    b.Navigation("SubmittedByUser");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.ParentStudent", b =>
                {
                    b.HasOne("SchoolSystem.Core.Models.User", "Parent")
                        .WithMany("ParentStudents")
                        .HasForeignKey("ParentUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolSystem.Core.Models.Student", "Student")
                        .WithMany("ParentStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.SemesterReport", b =>
                {
                    b.HasOne("SchoolSystem.Core.Models.Class", "Class")
                        .WithMany("SemesterReports")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolSystem.Core.Models.User", "SubmittedByUser")
                        .WithMany("SubmittedSemesterReports")
                        .HasForeignKey("SubmittedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Class");

                    b.Navigation("SubmittedByUser");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.SemesterReportEntry", b =>
                {
                    b.HasOne("SchoolSystem.Core.Models.SemesterReport", "Report")
                        .WithMany("Entries")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolSystem.Core.Models.Student", "Student")
                        .WithMany("SemesterReportEntries")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.SemesterScore", b =>
                {
                    b.HasOne("SchoolSystem.Core.Models.ClassSubject", "ClassSubject")
                        .WithMany("SemesterScores")
                        .HasForeignKey("ClassSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolSystem.Core.Models.Student", "Student")
                        .WithMany("SemesterScores")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassSubject");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.Student", b =>
                {
                    b.HasOne("SchoolSystem.Core.Models.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.UserRole", b =>
                {
                    b.HasOne("SchoolSystem.Core.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolSystem.Core.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.YearlyReport", b =>
                {
                    b.HasOne("SchoolSystem.Core.Models.Class", "Class")
                        .WithMany("YearlyReports")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolSystem.Core.Models.User", "SubmittedByUser")
                        .WithMany("SubmittedYearlyReports")
                        .HasForeignKey("SubmittedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Class");

                    b.Navigation("SubmittedByUser");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.YearlyReportEntry", b =>
                {
                    b.HasOne("SchoolSystem.Core.Models.YearlyReport", "Report")
                        .WithMany("Entries")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolSystem.Core.Models.Student", "Student")
                        .WithMany("YearlyReportEntries")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.YearlyScore", b =>
                {
                    b.HasOne("SchoolSystem.Core.Models.ClassSubject", "ClassSubject")
                        .WithMany("YearlyScores")
                        .HasForeignKey("ClassSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolSystem.Core.Models.Student", "Student")
                        .WithMany("YearlyScores")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassSubject");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.Class", b =>
                {
                    b.Navigation("ClassSubjects");

                    b.Navigation("MonthlyReports");

                    b.Navigation("SemesterReports");

                    b.Navigation("Students");

                    b.Navigation("YearlyReports");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.ClassSubject", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("GradebookEntries");

                    b.Navigation("MonthlyScores");

                    b.Navigation("SemesterScores");

                    b.Navigation("YearlyScores");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.Grade", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.MonthlyReport", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.SemesterReport", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.Student", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("GradebookEntries");

                    b.Navigation("MonthlyReportEntries");

                    b.Navigation("MonthlyScores");

                    b.Navigation("ParentStudents");

                    b.Navigation("SemesterReportEntries");

                    b.Navigation("SemesterScores");

                    b.Navigation("YearlyReportEntries");

                    b.Navigation("YearlyScores");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.Subject", b =>
                {
                    b.Navigation("ClassSubjects");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.User", b =>
                {
                    b.Navigation("HomeroomClasses");

                    b.Navigation("ParentFeedbacks");

                    b.Navigation("ParentStudents");

                    b.Navigation("SubmittedMonthlyReports");

                    b.Navigation("SubmittedMonthlyScores");

                    b.Navigation("SubmittedSemesterReports");

                    b.Navigation("SubmittedYearlyReports");

                    b.Navigation("TeachingClassSubjects");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SchoolSystem.Core.Models.YearlyReport", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Feedbacks");
                });
#pragma warning restore 612, 618
        }
    }
}
